name: macOS tests

on:
  push:
    branches:
      - master
    paths:
      - packages/**
      - examples/**
      - src/**
      - .github/**
      - lib.rs
      - Cargo.toml

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master
    paths:
      - packages/desktop/**
      - examples/**
      - src/**
      - .github/**
      - lib.rs
      - Cargo.toml

jobs:
  build-for-iOS:
    if: github.event.pull_request.draft == false
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - name: Add iOS targets
        run: rustup target add aarch64-apple-ios-sim
      - name: Test iOS targets
        run: cargo test --package desktop --target aarch64-apple-ios-sim --all --tests
